steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - api/Dockerfile
      - -t
      - ${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$SHORT_SHA
      - api

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$SHORT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image
      - ${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$SHORT_SHA
      - --region
      - ${_RUN_REGION}
      - --platform
      - managed
      - --allow-unauthenticated
      - --set-secrets
      - DATABASE_URL=DATABASE_URL:latest,JWT_SECRET=JWT_SECRET:latest
      - --set-env-vars
      - WEB_ORIGIN=${_WEB_ORIGIN},NODE_ENV=production

images:
  - ${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$SHORT_SHA

substitutions:
  _SERVICE: fleet-api
  _RUN_REGION: europe-west1
  _AR_REGION: europe-west1
  _AR_REPO: fleet-enterprise
  _WEB_ORIGIN: https://example-web-url.run.app
