import type { BotModuleDefinition, BotScenarioPreset } from './bot.types';

export const BOT_MODULE_REGISTRY: BotModuleDefinition[] = [
  {
    id: 'clients',
    label: 'Clienți',
    domain: 'crm',
    description: 'Organizații contractuale (Alpha, Beta).',
    operations: ['create', 'edit', 'delete'],
    maxPerOperation: 20,
    implemented: false,
    supportsMultiUser: true,
    supportsMobile: false,
  },
  {
    id: 'vehicles',
    label: 'Vehicule',
    domain: 'operations',
    description: 'Flotă pe diviziune — nr. înmatriculare, km, ITP.',
    operations: ['create', 'edit', 'delete'],
    optionFields: [
      {
        key: 'coherentOdometer',
        label: 'Lanț km coerent',
        type: 'boolean',
        defaultValue: true,
        hint: 'Odometru crescător pe vehicul.',
      },
    ],
    maxPerOperation: 30,
    dependencies: ['clients'],
    implemented: true,
    supportsMultiUser: true,
    supportsMobile: true,
  },
  {
    id: 'drivers',
    label: 'Șoferi',
    domain: 'crm',
    description: 'Șoferi și alocări vehicul.',
    operations: ['create', 'edit', 'delete'],
    maxPerOperation: 30,
    dependencies: ['clients', 'vehicles'],
    implemented: false,
    supportsMultiUser: true,
    supportsMobile: true,
  },
  {
    id: 'trips',
    label: 'Curse & parcurs',
    domain: 'operations',
    description: 'Curse cu km, rute și timeline logic.',
    operations: ['create', 'edit', 'delete'],
    optionFields: [
      {
        key: 'coherentOdometer',
        label: 'Lanț km coerent',
        type: 'boolean',
        defaultValue: true,
      },
      {
        key: 'closeOpenTrips',
        label: 'Închide curse deschise la edit',
        type: 'boolean',
        defaultValue: true,
      },
    ],
    maxPerOperation: 50,
    dependencies: ['vehicles'],
    implemented: true,
    supportsMultiUser: true,
    supportsMobile: true,
  },
  {
    id: 'costs',
    label: 'Costuri',
    domain: 'operations',
    description: 'Costuri operaționale (combustibil etc.).',
    operations: ['create', 'edit', 'delete'],
    maxPerOperation: 50,
    dependencies: ['vehicles', 'trips'],
    implemented: false,
    supportsMultiUser: true,
    supportsMobile: true,
  },
  {
    id: 'maintenance',
    label: 'Mentenanță',
    domain: 'operations',
    description: 'Intervenții și plan mentenanță.',
    operations: ['create', 'edit', 'delete'],
    maxPerOperation: 30,
    dependencies: ['vehicles'],
    implemented: false,
    supportsMultiUser: true,
    supportsMobile: false,
  },
  {
    id: 'documents',
    label: 'Documente flotă',
    domain: 'operations',
    description: 'RCA, CASCO, ITP, CIV.',
    operations: ['create', 'edit', 'delete'],
    maxPerOperation: 30,
    dependencies: ['vehicles'],
    implemented: false,
    supportsMultiUser: false,
    supportsMobile: false,
  },
  {
    id: 'reminders',
    label: 'Remindere',
    domain: 'operations',
    description: 'Acțiuni remindere legate de conformitate.',
    operations: ['create', 'edit', 'delete'],
    maxPerOperation: 30,
    dependencies: ['vehicles', 'documents'],
    implemented: false,
    supportsMultiUser: false,
    supportsMobile: true,
  },
  {
    id: 'tickets',
    label: 'Tichete CRM',
    domain: 'crm',
    description: 'Solicitări multi-nivel L0 → L1 → L★.',
    operations: ['create', 'edit', 'delete'],
    optionFields: [
      {
        key: 'processCapCoada',
        label: 'Proces cap–coadă',
        type: 'boolean',
        defaultValue: false,
        hint: 'Claim → comentariu → rutare → rezolvare.',
      },
      {
        key: 'scenarioType',
        label: 'Tip scenariu',
        type: 'select',
        options: [
          { value: 'damage', label: 'Daună' },
          { value: 'itp', label: 'ITP' },
          { value: 'maintenance', label: 'Mentenanță' },
          { value: 'document', label: 'Document' },
        ],
        defaultValue: 'itp',
      },
      {
        key: 'startLevel',
        label: 'Nivel start',
        type: 'select',
        options: [
          { value: 'L0', label: 'L0 — șofer' },
          { value: 'L1', label: 'L1 — manager client' },
        ],
        defaultValue: 'L0',
      },
    ],
    maxPerOperation: 20,
    dependencies: ['clients', 'vehicles', 'drivers'],
    implemented: false,
    supportsMultiUser: true,
    supportsMobile: true,
  },
  {
    id: 'ticket_messaging',
    label: 'Mesagerie tichet',
    domain: 'crm',
    description: 'Comentarii, reply, reacții.',
    operations: ['create', 'edit'],
    maxPerOperation: 50,
    dependencies: ['tickets'],
    implemented: false,
    supportsMultiUser: true,
    supportsMobile: true,
  },
];

export const BOT_SCENARIO_PRESETS: BotScenarioPreset[] = [
  {
    id: 'demo_minimal',
    label: 'Demo minim',
    description: 'Vehicule seed + curse coerente pe Alpha.',
    division: 'alpha',
    modules: {
      vehicles: { create: 0, edit: 2 },
      trips: { create: 5, options: { coherentOdometer: true } },
    },
  },
  {
    id: 'demo_crm',
    label: 'Demo CRM',
    description: 'Curse + tichete cap–coadă (când modulul e activ).',
    division: 'alpha',
    modules: {
      trips: { create: 3 },
      tickets: {
        create: 2,
        options: { processCapCoada: true, scenarioType: 'itp', startLevel: 'L0' },
      },
    },
  },
  {
    id: 'demo_stress_alpha',
    label: 'Stress Alpha',
    description: 'Volum mărit pe diviziunea Alpha.',
    division: 'alpha',
    modules: {
      vehicles: { create: 0, edit: 5 },
      trips: { create: 15, edit: 2 },
    },
  },
];

export const BOT_FAULT_CATALOG = [
  {
    id: 'rbac_viewer_write',
    label: 'RBAC — viewer încearcă scriere',
    description: 'Simulează POST ca tenant_viewer; așteptat 403.',
    moduleId: 'trips',
  },
  {
    id: 'validation_bad_odometer',
    label: 'Validare — km invalid',
    description: 'Odometru sfârșit < start; așteptat 400.',
    moduleId: 'trips',
  },
  {
    id: 'conflict_duplicate_reference',
    label: 'Conflict — referință duplicat',
    description: 'Aceeași referință cursă de două ori.',
    moduleId: 'trips',
  },
];

export function getBotModule(id: string): BotModuleDefinition | undefined {
  return BOT_MODULE_REGISTRY.find((m) => m.id === id);
}
