import type { IamStrategyNode } from './iam-strategy.types';

/** Hartă IAM canonică — sincronizată cu docs/identity-access-model.md §3.5 */
export function defaultIamStrategyNodes(): IamStrategyNode[] {
  return [
    {
      id: 'node-l-star-star',
      levelLabel: 'L**',
      title: 'Superadmin platformă',
      subtitle: 'Owner business & app (doar vendor)',
      tone: 'platform',
      badge: 'STRAT 0',
      examples: 'Cont manual · Neon / GCP',
      status: 'planificat',
      children: [],
    },
    {
      id: 'node-l-star',
      levelLabel: 'L*',
      title: 'Admin tenant (FlotaX)',
      subtitle: 'Administrare clienți: Alpha, Beta, Client_1…',
      tone: 'tenant',
      badge: 'STRAT 1',
      examples: 'admin@demo · flotax_admin@flotax',
      status: 'live',
      children: [
        {
          id: 'node-l-star-f',
          levelLabel: 'F',
          title: 'Financiar',
          subtitle: 'Deviz aprobare · cost · factură',
          tone: 'finance',
          profileCode: 'F',
          status: 'planificat',
        },
        {
          id: 'node-l-star-t',
          levelLabel: 'T',
          title: 'Tehnic',
          subtitle: 'Tichete · service · deviz edit',
          tone: 'tech',
          profileCode: 'T',
          status: 'planificat',
        },
        {
          id: 'node-l-star-g',
          levelLabel: 'G',
          title: 'Logistică',
          subtitle: 'Programator · curse · șoferi',
          tone: 'logistics',
          profileCode: 'G',
          status: 'planificat',
        },
        {
          id: 'node-l-star-full',
          levelLabel: 'full',
          title: 'Administrator full',
          subtitle: 'Toate capabilitățile L*',
          tone: 'full',
          profileCode: 'full',
          status: 'live',
        },
      ],
    },
    {
      id: 'node-l1',
      levelLabel: 'L1',
      title: 'Manager / angajat client',
      subtitle: 'Scoped la organizația contractuală (ex. Alpha SRL)',
      tone: 'client',
      badge: 'STRAT 2',
      examples: 'manager.alpha · client1flotax@flotax',
      status: 'live',
      children: [
        {
          id: 'node-l1-f',
          levelLabel: 'F',
          title: 'Financiar client',
          subtitle: 'Aprobă buget deviz',
          tone: 'finance',
          profileCode: 'F',
          status: 'planificat',
        },
        {
          id: 'node-l1-t',
          levelLabel: 'T',
          title: 'Tehnic client',
          subtitle: 'Tichete reparații · programări',
          tone: 'tech',
          profileCode: 'T',
          status: 'planificat',
        },
        {
          id: 'node-l1-g',
          levelLabel: 'G',
          title: 'Logistică client',
          subtitle: 'Curse · disponibilitate mașini',
          tone: 'logistics',
          profileCode: 'G',
          status: 'planificat',
        },
        {
          id: 'node-l1-full',
          levelLabel: 'full',
          title: 'Manager general',
          subtitle: 'Spec CRM / devize pilot',
          tone: 'full',
          profileCode: 'full',
          status: 'live',
        },
      ],
    },
    {
      id: 'node-l0',
      levelLabel: 'L0',
      title: 'Utilizator mașină / șofer',
      subtitle: 'Angajat client — vehicul(e) asignate',
      tone: 'driver',
      badge: 'STRAT 2',
      examples: 'sofer.alpha · client1flotaxsofer@flotax',
      status: 'live',
      children: [],
    },
    {
      id: 'node-r-axis',
      levelLabel: 'Axa R',
      title: 'Parteneri furnizori',
      subtitle: 'Nu sunt în ierarhia L a flotei',
      tone: 'partner',
      branchStyle: 'dashed',
      status: 'viitor',
      children: [
        {
          id: 'node-r-star',
          levelLabel: 'R*',
          title: 'Admin furnizor',
          subtitle: 'Service auto, piese, anvelope…',
          tone: 'partner',
          status: 'viitor',
        },
        {
          id: 'node-r1',
          levelLabel: 'R1',
          title: 'Operator furnizor',
          subtitle: 'Deviz, programare WO, factură',
          tone: 'partner',
          status: 'viitor',
        },
        {
          id: 'node-r0',
          levelLabel: 'R0',
          title: 'Utilizator limitat',
          subtitle: 'Vizualizare comenzi alocate',
          tone: 'partner',
          status: 'viitor',
        },
      ],
    },
  ];
}

export function cloneDefaultIamStrategyNodes(): IamStrategyNode[] {
  return JSON.parse(JSON.stringify(defaultIamStrategyNodes())) as IamStrategyNode[];
}
